### ISSUE TITLE
Use a relative path

### ISSUE THREAD

**Issue by henrikmdev** [samus9001/Quiz-Maker-Exercise#10] opened 2023-06-07 03:27 UTC
https://github.com/samus9001/Quiz-Maker-Exercise/blob/8d707b9956ab9938756c40fd63dc7f5352d873d6/Program.cs#L16

We want to be able to test your code too and this is a specific path in your computer. So use a relative path so we can test it.

**Comment by samus9001** [comment] 2023-06-11 13:34
duplicate of #9

**Closed by samus9001** 2023-06-11 13:34 UTC
